Site/Controllers/MyWorksController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Site.Code;
using Site.Models;
using _Data.Models;

namespace Site.Controllers
{
    public class MyWorksController : BaseController
    {
        public ActionResult List(string id)
        {
            List<Product> model;

            if (Guid.TryParse(id, out var idGuid))
            {
                var typeList = GetChildTypes(idGuid);
                typeList.Add(idGuid);
                
                model = db.Products.Where(i => typeList.Contains(i.ProductTypeId)).ToList();
            }
            else
            {
                model = db.Products.ToList();
            }

            ViewBag.ProductTypes = db.ProductTypes.Where(i => i.IsActive).ToList();

            return View(model);
        }

        public ActionResult Details(Guid id)
        {
            var model = db.Products.Find(id);

            return View(model);
        }



        public ActionResult Image(Guid id)
        {
            var m = new ImageController();
            return m.Mark(new ImageModel { Id = id, AppDataDir = "Product", Mark = Server.MapPath("~/Content/Images/mark.png"), MarkPercent = 50});
        }









        private List<Guid> GetChildTypes(Guid id)
        {
            var list = db.ProductTypes.Where(i => i.ProductTypeId == id).Select(i => i.Id).ToList();
            if (list.Any())
            {
                var cl = new List<Guid>();
                foreach (var i in list)
                {
                    cl.AddRange(GetChildTypes(i));
                }
                list.AddRange(cl);
            }
            return list;
        }

    }
}

Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>

    <div>
        <header>
            <div class="container">
                <div class="d-flex justify-content-between">
                    <div>


                        <nav class="navbar navbar-expand-lg navbar-light bg-light">
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navBarMain" aria-controls="navBarMain" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="collapse navbar-collapse" id="navBarMain">
                                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                                    <li class="nav-item active">
                                        @Html.ActionLink(" ", "Index", "Home", null, new { @class = "nav-link icon-home" })
                                    </li>
                                    <li class="nav-item">
                                        @Html.ActionLink("Мои работы", "List", "MyWorks", null, new { @class = "nav-link" })
                                    </li>
                                    <li class="nav-item">
                                        @Html.ActionLink("Новости", "", "", null, new { @class = "nav-link" })
                                    </li>
                                    <li class="nav-item">
                                        @Html.ActionLink("Статьи", "", "", null, new { @class = "nav-link" })
                                    </li>
                                    <li class="nav-item">
                                        @Html.ActionLink("Контакты", "", "", null, new { @class = "nav-link" })
                                    </li>
                                    <li class="nav-item">
                                        @Html.ActionLink("Кукла", "Index", "Dummy", null, new { @class = "nav-link" })
                                    </li>
                                </ul>
                            </div>
                        </nav>


                    </div>
                    <div>

                        <nav class="navbar navbar-expand-lg navbar-light bg-light">
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                                    <li class="nav-item">
                                        @Html.ActionLink("Войти", "", "", new { @class = "nav-link" })
                                    </li>
                                    <li class="nav-item">
                                        <span class="nav-link">или</span>
                                        
                                    </li>
                                    <li class="nav-item">
                                        @Html.ActionLink("Зарегистрироваться", "", "", new { @class = "nav-link" })
                                    </li>
                                </ul>
                            </div>
                        </nav>

                    </div>
                </div>
                <div class="p-5">
                    @Html.ActionLink("З.А.П.И.С.А.Т.Ь.С.Я", "", "", new { @class = "d-table btn btn-success btn-lg m-auto" })
                </div>
            </div>
        </header>
        <main>
            <div class="container">
                <div class="row">
                    <div class="col">

                        @RenderBody()

                    </div>
                </div>
            </div>
        </main>
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col">

                        <p>&copy; 2016-@DateTime.Now.Year MaryNails.ru</p>

                    </div>
                </div>
            </div>
        </footer>
    </div>








@Scripts.Render("~/bundles/bootstrap")
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
@RenderSection("scripts", required: false)
</body>
</html>