Admin/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Admin.Code;
using Admin.Models;
using Newtonsoft.Json;

namespace Admin.Controllers
{
    [Authorize]
    public class FilesController : BaseController
    {
        private readonly string _appData = ConfigurationManager.AppSettings["AppData"];


        public FilesController()
        {
            _appData = string.IsNullOrEmpty(_appData) ? Server.MapPath("~/App_Data/") : _appData;
        }



        public ActionResult Index(FileModel model)
        {
            var prefix = string.IsNullOrEmpty(model.Prefix) ? string.Empty : model.Prefix + "_";

            var url = Path.Combine(_appData, model.AppDataDir);
            Directory.CreateDirectory(url);
            var fileUrl = Directory.GetFiles(url, prefix + model.Id + "*").FirstOrDefault();

            model.IsFileExists = !string.IsNullOrEmpty(fileUrl);

            ViewBag.json = JsonConvert.SerializeObject(model);


            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Upload(FileModel model)
        {
            var prefix = string.IsNullOrEmpty(model.Prefix) ? string.Empty : model.Prefix + "_";

            try
            {
                foreach (string f in Request.Files)
                {
                    var file = Request.Files[f];

                    if (file != null)
                    {
                        if (new[] { "image/jpeg", "image/png", "image/gif", "image/bmp" }.Contains(file.ContentType))
                        {
                            using (var image = Image.FromStream(file.InputStream))
                            {

                                if (model.ImageFixWidth + model.ImageFixHeight > 0)
                                {
                                    if (!(model.ImageFixWidth == image.Width && model.ImageFixHeight == image.Height))
                                    {
                                        ViewBag.Error = $"Размер изображения должен быть {model.ImageFixWidth}x{model.ImageFixHeight} не больше не меньше!";
                                        goto Return;
                                    }
                                }
                                else if (model.ImageMaxWidth + model.ImageMaxHeight > 0)
                                {
                                    if (model.ImageMaxWidth > image.Width && model.ImageMaxHeight > image.Height)
                                    {
                                        ViewBag.Error = "Изображение слишком маленькое.";
                                        goto Return;
                                    }
                                }
                                
                                try
                                {
                                    var url = Path.Combine(_appData, model.AppDataDir);
                                    Directory.CreateDirectory(url);
                                    var ext = file.FileName.Split('.').Last();
                                    DeleteFile(model);
                                    
                                    if (model.ImageMaxWidth + model.ImageMaxHeight > 0)
                                    {
                                        using (var bmp = ResizeImage((Bitmap)image, model.ImageMaxWidth, model.ImageMaxHeight))
                                        {
                                            bmp.Save(Path.Combine(url, prefix + model.Id + "." + ext), image.RawFormat);
                                        }
                                        goto Return;
                                    }
                                    
                                    image.Save(Path.Combine(url, prefix + model.Id + "." + ext), image.RawFormat);
                                }
                                catch (Exception exc)
                                {
                                    ViewBag.Error = exc.Message;
                                    goto Return;
                                }
                            }
                        }
                    }
                }
            }
            catch
            {
                ViewBag.Error = "Некорректный формат изображения.";
                goto Return;
            }

            Return:

            ViewBag.json = JsonConvert.SerializeObject(model);

            return View("Index", model);
        }



        


        [HttpGet]
        public ActionResult GetImage(FileModel model)
        {
            var prefix = string.IsNullOrEmpty(model.Prefix) ? string.Empty : model.Prefix + "_";

            var url = string.IsNullOrEmpty(model.AppDataDir) ? _appData : Path.Combine(_appData, model.AppDataDir);
            Directory.CreateDirectory(url);
            var fileUrl = Directory.GetFiles(url, prefix + model.Id + "*").FirstOrDefault();
            if (string.IsNullOrEmpty(fileUrl))
            {
                fileUrl = Path.Combine(Server.MapPath("~/Content/Images/"), "No_image_available.jpg");
            }
            
            return File(fileUrl, MimeMapping.GetMimeMapping(fileUrl));
        }
        
        public void DeleteFile(FileModel model)
        {
            var prefix = string.IsNullOrEmpty(model.Prefix) ? string.Empty : model.Prefix + "_";

            var url = string.IsNullOrEmpty(model.AppDataDir) ? _appData : Path.Combine(_appData, model.AppDataDir);
            var files = Directory.GetFiles(url, prefix + model.Id + "*");
            if (files.Any())
            {
                foreach (var file in files)
                {
                    System.IO.File.Delete(file);
                }
            }
        }










        private static Bitmap ResizeImage(Bitmap src, int newWidth, int newHeight)
        {
            if (src.Width > newWidth || src.Height > newHeight)
            {
                int width = newWidth, height = newHeight;

                if (src.Width > newWidth && src.Height <= newHeight)
                {
                    height = newWidth * src.Height / src.Width;
                }
                else if (src.Width <= newWidth && src.Height > newHeight)
                {
                    width = newHeight * src.Width / src.Height;
                }
                else
                {
                    if (src.Width - newWidth > src.Height - newHeight)
                    {
                        height = newWidth * src.Height / src.Width;

                    }
                    else
                    {
                        width = newHeight * src.Width / src.Height;
                    }
                }
                try
                {
                    var bitmap = new Bitmap(width, height);
                    using (var graphics = Graphics.FromImage(bitmap))
                    {
                        graphics.DrawImage(src, new Rectangle(0, 0, width, height));
                    }
                    return bitmap;

                }
                catch (Exception exc)
                {
                    Console.WriteLine(exc);
                }
            }

            return src;
        }







        public ActionResult FileListForItem(FileModel model)
        {
            try
            {
                var url = Path.Combine(_appData, model.AppDataDir, model.Id.ToString());
                Directory.CreateDirectory(url);
                model.FileUrl = Directory.GetFiles(url, "*");

                ViewBag.json = JsonConvert.SerializeObject(model);
            }
            catch (Exception exc)
            {
                _logger.Error(exc);
            }
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult UploadFileForItem(FileModel model)
        {
            try
            {
                var url = Path.Combine(_appData, model.AppDataDir, model.Id.ToString());

                foreach (string f in Request.Files)
                {
                    var file = Request.Files[f];

                    var fileName = Path.GetFileName(file?.FileName);

                    if (fileName != null)
                    {
                        file.SaveAs(Path.Combine(url, fileName));
                    }
                }
            }
            catch (Exception exc)
            {
                _logger.Error(exc);
            }
            return RedirectToAction("FileListForItem", model);
        }

        [HttpPost]
        public ActionResult DeleteFileForItem(FileModel model)
        {
            try
            {
                var filePath = Path.Combine(_appData, model.AppDataDir, model.Id.ToString(), model.FileName);

                if (System.IO.File.Exists(filePath)) System.IO.File.Delete(filePath);
            }
            catch (Exception exc)
            {
                _logger.Error(exc);
            }

            return RedirectToAction("FileListForItem", model);
        }

        [HttpGet]
        public ActionResult GetFile(FileModel model)
        {
            try
            {
                var url = string.IsNullOrEmpty(model.AppDataDir) ? _appData : Path.Combine(_appData, model.AppDataDir);

                Directory.CreateDirectory(url);
                
                var fileUrl = Directory.GetFiles(Path.Combine(url, model.Id.ToString()), model.FileName);

                if (fileUrl.Length > 0)
                {
                    switch (model.Param)
                    {
                        case "view":
                                return File(fileUrl[0], MimeMapping.GetMimeMapping(fileUrl[0]));
                            break;
                        default:
                                goto theend;
                            break;
                    }

Admin/Controllers/NailDesignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Admin.Code;
using Admin.Code.Utils;
using Admin.Models;
using _Data.Models;

namespace Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class NailDesignController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            var search = (string)Session["NailDesignSearch"];

            var model = string.IsNullOrEmpty(search) ? db.NailDesigns : db.NailDesigns.Where(i => i.Name.Contains(search));

            var newModel = new List<NailDesignModel>();

            foreach (var item in model)
            {
                newModel.Add(new NailDesignModel
                {
                    Id = item.Id,
                    Name = item.Name,
                    TimeOut = TimeUtils.TimeFromUt(item.TimeOut),
                    Price = item.Price,
                    IsActive = item.IsActive,
                });
            }

            return PartialView(newModel);
        }

        public ActionResult Search()
        {
            return PartialView(new SearchModel { Text = string.IsNullOrEmpty((string)Session["NailDesignSearch"]) ? string.Empty : (string)Session["NailDesignSearch"] });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Search(SearchModel request)
        {
            Session["NailDesignSearch"] = request.Text;

            return RedirectToAction("List");
        }

        public ActionResult Create()
        {
            var model = new NailDesignModel();

            Binder.Bind(new NailDesign(), ref model);

            model.TimeOut = "00:00";

            InitFilds();

            return PartialView(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NailDesignRequestModel request)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var model = new NailDesign
                    {
                        Id = request.Id,
                        Name = request.Name,
                        TimeOut = TimeUtils.TimeToUt(request.TimeOut),
                        Price = request.Price,
                        IsActive = true
                    };

                    if (request.NailDesignTypesGuids != null)
                    {
                        var ndt = db.NailDesignTypes.Where(i => request.NailDesignTypesGuids.Contains(i.Id)).ToList();

                        for (var i = ndt.Count - 1; i >= 0; i--)
                        {
                            model.NailDesignTypes.Add(ndt[i]);
                        }
                    }
                    
                    db.NailDesigns.Add(model);
                    
                    db.SaveChanges();

                    return RedirectToAction("List");
                }
                catch (Exception exc)
                {
                    ModelState.AddModelError("", "Что то пошло не так.");
                }
            }

            InitFilds();

            return PartialView(request);
        }

        public ActionResult Edit(Guid id)
        {
            var item = db.NailDesigns.Find(id);
            if (item == null) return RedirectToAction("List");

            var model = new NailDesignModel();

            Binder.Bind(item, ref model);

            model.TimeOut = TimeUtils.TimeFromUt(item.TimeOut);

            InitFilds();

            return PartialView(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(NailDesignRequestModel request)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var model = db.NailDesigns.Find(request.Id);
                    
                    model.Name = request.Name;
                    model.TimeOut = TimeUtils.TimeToUt(request.TimeOut);
                    model.Price = request.Price;

                    var ndt = db.NailDesignTypes.Where(i => request.NailDesignTypesGuids.Contains(i.Id)).ToList();
                    model.NailDesignTypes.Clear();
                    for (var i = ndt.Count - 1; i >= 0; i--)
                    {
                        model.NailDesignTypes.Add(ndt[i]);
                    }

                    db.SaveChanges();

                    return RedirectToAction("List");
                }
                catch (Exception exc)
                {
                    Console.WriteLine(exc);
                }
            }

            InitFilds();

            return PartialView(request);
        }

        public ActionResult Delete(Guid id)
        {
            try
            {
                var item = db.NailDesigns.Find(id);
                if (item != null)
                {
                    db.NailDesigns.Remove(item);
                    db.SaveChanges();
                }
            }
            catch (Exception exc)
            {
                _logger.Error(exc);
            }
            return RedirectToAction("List");
        }

        public ActionResult ChangeVisibility(Guid id)
        {
            try
            {
                var item = db.NailDesigns.Find(id);
                if (item != null)
                {
                    item.IsActive = !item.IsActive;
                    db.SaveChanges();
                }
            }
            catch (Exception exc)
            {
                _logger.Error(exc);
            }
            return RedirectToAction("List");
        }

        private void InitFilds()
        {
            ViewBag.NailDesignTypes = db.NailDesignTypes.Where(i => i.IsActive).ToList();
        }
    }
}

Admin/Views/NailDesign/Create.cshtml
@using Admin.Models
@using _Data.Models
@model Admin.Models.NailDesignModel
@{
    var nailDesignTypes = (List<NailDesignType>)ViewBag.NailDesignTypes;

    ViewBag.Title = "Добавить новый дизайн";
}

<h2 class="page-title">@ViewBag.Title</h2>

@using (Ajax.BeginForm("Create", "NailDesign", null, new AjaxOptions { UpdateTargetId = "action-body" }))
{
    @Html.HiddenFor(m => m.Id)

    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col">
            @Html.ValidationSummary()
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(m => m.Name, new { @class = "col-3 col-form-label" })
        <div class="col">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </div>
    </div>


    <div class="form-group row">
        @Html.LabelFor(m => m.TimeOut, new { @class = "col-3 col-form-label" })
        <div class="col">
            @Html.TextBoxFor(m => m.TimeOut, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(m => m.Price, new { @class = "col-3 col-form-label" })
        <div class="col">
            @Html.TextBoxFor(m => m.Price, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group row">
        <label class="col-3 col-form-label">Фотография</label>
        <div class="col">
            @Html.Action("Index", "Files", new FileModel { Id = Model.Id, AppDataDir = "NailDesign", ImageFixWidth = 53, ImageFixHeight = 118 })
        </div>
    </div>

    <div class="form-group row">
        <label class="col-3 col-form-label">К каким типам относится?</label>
        <div class="col">
            <div class="d-inline-flex flex-column pt-2 mb-3">
                @if (nailDesignTypes != null)
                {
                    foreach (var item in nailDesignTypes)
                    {
                        <div class="d-inline-flex align-items-center">
                            <div class="pr-2">
                                @if (Model.NailDesignTypes != null && Model.NailDesignTypes.Any(i => i.Id == item.Id))
                                {
                                    <input class="d-block" id="NailDesignTypesGuids[]" type="checkbox" name="NailDesignTypesGuids[]" checked="checked" value="@item.Id"/>
                                }
                                else
                                {
                                    <input class="d-block" id="NailDesignTypesGuids[]" type="checkbox" name="NailDesignTypesGuids[]" value="@item.Id"/>
                                }

                            </div>
                            <div class="font-italic">@item.Name</div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>



    <div class="form-group row">
        <div class="col-3"></div>
        <div class="col">
            <div class="row">
                <div class="col-auto mr-auto">
                    <button type="submit" class="btn btn-primary">Добавить</button>
                </div>
                <div class="col-auto">
                    @Ajax.ActionLink("Отмена", "List", "NailDesign", null, new AjaxOptions { UpdateTargetId = "action-body" }, new { @class = "btn btn-danger" })
                </div>
            </div>
        </div>
    </div>
}

Admin/Views/NailDesign/Edit.cshtml
@using Admin.Models
@using _Data.Models
@model Admin.Models.NailDesignModel
@{
    var nailDesignTypes = (List<NailDesignType>)ViewBag.NailDesignTypes;

    ViewBag.Title = "Редактирование дизайа - " + Model.Name;
}

<h2 class="page-title">@ViewBag.Title</h2>

@using (Ajax.BeginForm("Edit", "NailDesign", null, new AjaxOptions { UpdateTargetId = "action-body" }))
{
    @Html.HiddenFor(m => m.Id)

    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col">
            @Html.ValidationSummary()
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(m => m.Name, new { @class = "col-3 col-form-label" })
        <div class="col">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(m => m.TimeOut, new { @class = "col-3 col-form-label" })
        <div class="col">
            @Html.TextBoxFor(m => m.TimeOut, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group row">
        @Html.LabelFor(m => m.Price, new { @class = "col-3 col-form-label" })
        <div class="col">
            @Html.TextBoxFor(m => m.Price, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group row">
        <label class="col-3 col-form-label">Фотография</label>
        <div class="col">
            @Html.Action("Index", "Files", new FileModel { Id = Model.Id, AppDataDir = "NailDesign", ImageFixWidth = 53, ImageFixHeight = 118 })
        </div>
    </div>

    <div class="form-group row">
        <label class="col-3 col-form-label">К каким типам относится?</label>
        <div class="col">
            <div class="d-inline-flex flex-column pt-2 mb-3">
                @foreach (var item in nailDesignTypes)
                {
                    <div class="d-inline-flex align-items-center">
                        <div class="pr-2">
                            @if (Model.NailDesignTypes.Any(i => i.Id == item.Id))
                            {
                                <input class="d-block" id="NailDesignTypesGuids[]" type="checkbox" name="NailDesignTypesGuids[]" checked="checked" value="@item.Id" />
                            }
                            else
                            {
                                <input class="d-block" id="NailDesignTypesGuids[]" type="checkbox" name="NailDesignTypesGuids[]" value="@item.Id" />
                            }

                        </div>
                        <div class="font-italic">@item.Name</div>
                    </div>
                }
            </div>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-3"></div>
        <div class="col">
            <div class="row">
                <div class="col-auto mr-auto">
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </div>
                <div class="col-auto">
                    @Ajax.ActionLink("Отмена", "List", "NailDesign", null, new AjaxOptions { UpdateTargetId = "action-body" }, new { @class = "btn btn-danger" })
                </div>
            </div>
        </div>
    </div>
}

Admin/Views/NailDesign/Index.cshtml
<div id="action-body">
    @Html.Action("List")
</div>

Admin/Views/NailDesign/List.cshtml
@using Admin.Models
@model IEnumerable<NailDesignModel>
@{
    ViewBag.Title = "Дизыйны";
}

<h2 class="page-title">@ViewBag.Title</h2>

<hr />

<div class="d-flex justify-content-between">
    <div>
        @Ajax.ActionLink(" ", "Create", "NailDesign", null, new AjaxOptions { UpdateTargetId = "action-body" }, new { @class = "icon-plus btn btn-outline-success" })
    </div>
    <div>
        @Html.Action("Search")
    </div>
</div>




@if (Model.Any())
{
    <table class="table table-hover table-bordered mt-3 mb-3">
        <thead class="thead-dark">
        <tr>
            <th scope="col">Название</th>
            <th scope="col">Затрачиваемое время</th>
            <th scope="col">Цена</th>
            <th scope="col">Модель</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="align-top">@item.Name</td>
                <td class="align-top">@item.TimeOut</td>
                <td class="align-top">@item.Price</td>
                <td class="align-top">
                    <img class="img-fluid img-thumbnail" src="@Url.Action("GetImage", "Files", new FileModel { Id = item.Id, AppDataDir = "NailDesign" })" />
                </td>
                <td class="align-top text-right" width="1">
                    <div class="d-inline-flex">
                        <div class="pr-1">
                            @Ajax.ActionLink(" ", "Edit", "NailDesign", new {id = item.Id}, new AjaxOptions {UpdateTargetId = "action-body"}, new {@class = "btn btn-outline-primary btn-sm icon-edit", title = "Редактировать"})
                        </div>
                        <div class="pr-1">
                            @Ajax.ActionLink(" ", "ChangeVisibility", "NailDesign", new {id = item.Id}, new AjaxOptions {UpdateTargetId = "action-body"}, item.IsActive ? new {@class = "btn btn-outline-dark btn-sm icon-eye-show", title = "Скрыть"} : new {@class = "btn btn-outline-secondary btn-sm icon-eye-hide", title = "Показать"})
                        </div>
                        <div>
                            @Ajax.ActionLink(" ", "Delete", "NailDesign", new { id = item.Id }, new AjaxOptions { UpdateTargetId = "action-body", Confirm = $"Удаление '{item.Name}' \n\nВ действительно хотите удалить эту запись?" }, new { @class = "btn btn-outline-danger btn-sm icon-remove", title = "Удалить" })
                        </div>
                    </div>
                </td>
            </tr>
        }
        </tbody>
    </table>


    @Ajax.ActionLink(" ", "Create", "NailDesign", null, new AjaxOptions { UpdateTargetId = "action-body" }, new { @class = "icon-plus btn btn-outline-success" })
}

Admin/Views/NailDesign/Search.cshtml
@model Admin.Models.SearchModel
@{
    Layout = null;
}

@using (Ajax.BeginForm("Search", "NailDesign", null, new AjaxOptions { UpdateTargetId = "action-body" }, new { @class = "d-inline-flex" }))
{
    @Html.AntiForgeryToken()
    <div class="pr-1">
        @Html.TextBoxFor(m => m.Text, new { @class = "form-control form-control-sm", placeholder = "Искать..." })
    </div>
    <div>
        <button type="submit" class="btn btn-outline-secondary btn-sm">Найти</button>
    </div>
}